In [4]:
import numpy as np
import matplotlib.pyplot as plt

# Experimento N° 1, Capacidad de un CD

In [5]:
#datos obtenidos
d=np.zeros([6,2])
d[0]=np.array([21.5,12.0]) #d[i]=np.array([distancia pantalla-cd,distancia ordenes de difraccion])
d[1]=np.array([25,14.1])
d[2]=np.array([30,16.6])
d[3]=np.array([35,19.5])
d[4]=np.array([40,22.2])
d[5]=np.array([45,24.5])
d

array([[21.5, 12. ],
       [25. , 14.1],
       [30. , 16.6],
       [35. , 19.5],
       [40. , 22.2],
       [45. , 24.5]])

In [6]:
d[1,1]

14.1

In [7]:
def atan(x,y): #theta
    return np.arctan(y/x)

In [8]:
dx=0.05
dy=0.05

In [9]:
def ET(x,y):#error theta
    return np.sqrt(((np.abs(y/((y**2)+(x**2))))*(dx**2))**2 + ((np.abs(x/((y**2)+(x**2))))*(dy))**2)

In [10]:
theta=np.zeros([6,2]) #theta mas el error de theta
#etheta=np.zeros([6,1])
for i in range(0,6):
    theta[i]=atan(d[i,0], d[i,1]),ET(d[i,0], d[i,1])
    #etheta[i]=ET(d[i,0], d[i,1])
print(theta)

[[0.50907089 0.00177389]
 [0.5135282  0.00151794]
 [0.50539879 0.00127648]
 [0.50831063 0.0010906 ]
 [0.50667388 0.00095601]
 [0.49856791 0.00085738]]


In [11]:
def sen(t):
    return np.sin(t)

In [12]:
def es(t,et):
    return np.cos(t)*(et)

In [13]:
seno=np.zeros([6,2])
for i in range(0,6):
    seno[i]=sen(theta[i,0]),es(theta[i,0],theta[i,1])
print(seno)

[[0.48736616 0.00154895]
 [0.49125342 0.00132215]
 [0.48415641 0.00111689]
 [0.48670216 0.00095271]
 [0.4852717  0.0008359 ]
 [0.47816827 0.00075301]]


$$ d_s = \frac{\lambda}{sen\theta}$$

In [14]:
l=np.array([630,640,650])*10**(-9)
ll=np.mean(l)
std=10**(-8)

In [15]:
def dsurco(ll,seno):
    return ll/seno

In [16]:
def error(ll,seno,std,etheta):
    return np.sqrt(((1/(seno))**2)*(std**2) + ((((ll**2)*(1-seno**2))/(seno**4))*(etheta**2)))

In [17]:
ds=np.zeros([6,2])
for i in range(0,6):
    ds[i]=dsurco(ll,seno[i,0]),error(ll,seno[i,0],std,theta[i,1])
print(ds)

[[1.31318104e-06 2.09386155e-08]
 [1.30278992e-06 2.06558647e-08]
 [1.32188686e-06 2.08783792e-08]
 [1.31497260e-06 2.07070548e-08]
 [1.31884881e-06 2.07318567e-08]
 [1.33844097e-06 2.10190872e-08]]


In [18]:
resurco=np.zeros([1,6]) #resultadossurco
for i in range(0,6):
    resurco[0,i]=ds[i,0]
print(resurco)

[[1.31318104e-06 1.30278992e-06 1.32188686e-06 1.31497260e-06
  1.31884881e-06 1.33844097e-06]]


In [19]:
print(np.mean(resurco)) # promedio de resultados
print(np.std(resurco)) # desviacion estandar 
# como el error obtenido de la propagacion de errores es mayor que la desviacion estandar, el valor del surco calculado mas su error será
print('La estimacion de la  distancia entre surcos junto a su error está dada por')
print('1.32 $\\times$ 10e-6[m] $\pm$ 0.02 $\\times$ 10e-6[m] ')

1.3183533681090741e-06
1.0775329290462505e-08
1.32 $\times$ 10e-6[m] $\pm$ 0.02 $\times$ 10e-6[m] 


# Experimento N°2 pelo

In [20]:
dd=np.zeros([6,2])
dd[0]=([40,0.5])
dd[1]=([50,0.6])
dd[2]=([60,0.7])
dd[3]=([70,0.8])
dd[4]=([80,1.0])
dd[5]=([90,1.2])

In [21]:
dd

array([[40. ,  0.5],
       [50. ,  0.6],
       [60. ,  0.7],
       [70. ,  0.8],
       [80. ,  1. ],
       [90. ,  1.2]])

In [22]:
thetap=np.zeros([6,2]) #theta mas el error de theta
for i in range(0,6):
    thetap[i]=atan(dd[i,0], dd[i,1]),ET(dd[i,0], d[i,1])
    #etheta[i]=ET(d[i,0], d[i,1])
print(thetap)

[[0.01249935 0.00114692]
 [0.01199942 0.00092643]
 [0.01166614 0.00077416]
 [0.01142807 0.00066291]
 [0.01249935 0.00058037]
 [0.01333254 0.00051727]]


In [23]:
senop=np.zeros([6,2])
for i in range(0,6):
    senop[i]=sen(thetap[i,0]),es(thetap[i,0],thetap[i,1])
print(senop)

[[0.01249902 0.00114683]
 [0.01199914 0.00092636]
 [0.01166587 0.0007741 ]
 [0.01142783 0.00066287]
 [0.01249902 0.00058032]
 [0.01333215 0.00051723]]


In [24]:
dp=np.zeros([6,2])
for i in range(0,6):
    dp[i]=dsurco(ll,senop[i,0]),error(ll,senop[i,0],std,senop[i,1])
print(dp)
dp[:,0]

[[5.12039998e-05 4.76541713e-06]
 [5.33371732e-05 4.20094512e-06]
 [5.48608761e-05 3.73968027e-06]
 [5.60036570e-05 3.36406979e-06]
 [5.12039998e-05 2.50821114e-06]
 [4.80042665e-05 2.00757164e-06]]


array([5.12039998e-05, 5.33371732e-05, 5.48608761e-05, 5.60036570e-05,
       5.12039998e-05, 4.80042665e-05])

In [27]:
repelo=np.zeros([1,6])
for i in range(0,6):
    repelo[0,i]=dp[i,0]
repelo

array([[5.12039998e-05, 5.33371732e-05, 5.48608761e-05, 5.60036570e-05,
        5.12039998e-05, 4.80042665e-05]])

In [29]:
print(np.mean(repelo))
print(np.std(repelo))
#Como la desviacion estandar es menor que el mayor de los errores de propagacion obtenidos, el ancho de pelo calculado es
print('La estimacion del ancho del pelo junto a su error esta dado por')
print("52 $\\times$ 10e-6[m] $\pm$ 5$\\times$ 10e-6[m]")

5.2435662074429584e-05
2.648780341679132e-06
La estimacion del ancho del pelo junto a su error esta dado por
52 $\times$ 10e-6[m] $\pm$ 5$\times$ 10e-6[m]
